### ISSUE TITLE
`Var` inconsistente no exemplo `fib.json`

### ISSUE THREAD

**Issue by edusporto** [aripiprazole/rinha-de-compiler#11]
Boa noite! Queria começar essa issue parabenizando o esforço de vocês na preparação desta rinha, dá pra ver que deu bastante trabalho :)

Sobre o problema, [nesta linha](https://github.com/aripiprazole/rinha-de-compiler/blob/8f369119e38f3c9b55bbbc6289a3df0b20629d5a/files/fib.json#L6C21-L6C21) há um termo da variante `Var` que não possui o atributo `kind`, enquanto [nesta linha](https://github.com/aripiprazole/rinha-de-compiler/blob/8f369119e38f3c9b55bbbc6289a3df0b20629d5a/files/fib.json#L22C27-L22C27) possui. Acho que o esperado seria que todas as instâncias de `Var` tivessem um `kind`.

**Comment by allanmaral** [comment]
Boa noite, @edusporto! Na verdade existem dois `Var`s: um é o [struct `Var`](https://github.com/aripiprazole/rinha-de-compiler/blob/8f369119e38f3c9b55bbbc6289a3df0b20629d5a/src/parser.rs#L12C1-L15), e a outra é a [variante do enum `Term`](https://github.com/aripiprazole/rinha-de-compiler/blob/8f369119e38f3c9b55bbbc6289a3df0b20629d5a/src/ast.rs#L260C5-L260C28). Na serialização, só a variante do enum é que recebe o atributo `kind`. 

[Nessa linha](https://github.com/aripiprazole/rinha-de-compiler/blob/8f369119e38f3c9b55bbbc6289a3df0b20629d5a/files/fib.json#L6C21-L6C21) o json é a representação do struct `Var` que é o atributo `name` do struct `Let` e [nessa linha](https://github.com/aripiprazole/rinha-de-compiler/blob/8f369119e38f3c9b55bbbc6289a3df0b20629d5a/files/fib.json#L22C27-L22C27), o enum `Term::Var`.

**Comment by algebraic-sofia** [comment]
Muito obrigado pela observação. A resposta do @allanmaral está correta e isso foi especificado como descrição no SPECS.md.
