### ISSUE TITLE
Dúvida sobre Print(Print(x))

### ISSUE THREAD

**Issue by Danfs64** [aripiprazole/rinha-de-compiler#120]
No Discord, eu levantei a dúvida de "O que acontece na chamada `Print(Print(x))`".

A resposta para esse pergunta é:
Uma chamada de print, além de printar o valor, retorna esse valor. Logo, um `print(print(x))` deveria printar `x` duas vezes

**Comment by ricardobortoti** [comment]
> No Discord, eu levantei a dúvida de "O que acontece na chamada `Print(Print(x))`".
> 
> A resposta para esse pergunta é: Uma chamada de print, além de printar o valor, retorna esse valor. Logo, um `print(print(x))` deveria printar `x` duas vezes

ou seja:

```
let x = print("hello");
print(x)
```

printaria "hello" 2 vezes?

**Comment by Danfs64** [comment]
>printaria "hello" 2 vezes?

Precisamente.
