### ISSUE TITLE
Ajuda para gerar novas AST

### ISSUE THREAD

**Issue by filipemelo2002** [aripiprazole/rinha-de-compiler#173]
Pessoal, sou um pouco leigo com Rust (na verdade não sei absolutamente nada). Como faço pra gerar uma nova AST para um script teste meu?

**Comment by blenderaiser** [comment]
Acho que este vídeo pode te ajudar: https://www.youtube.com/watch?v=FbCdhicY3sk

**Comment by ErnaneJ** [comment]
Depois de ter certeza de que está com o Rust [instalado](https://www.rust-lang.org/tools/install). Instale a ferramente `rinha`

```bash
cargo install rinha
```

Com isso você pode gerar seu JSON executando o seguinte

```
rinha ./var/rinha/<FILE_NAME>.rinha > ./var/rinha/<FILE_NAME>.rinha.json
```

_*considere `./var/rinha/<FILE_NAME>.rinha` o seu código escrito na sintaxe rinha e o `./var/rinha/<FILE_NAME>.rinha.json` a sua AST equivalente em JSON que corresponde ao conteúdo desse arquivo._

Boa sorte! :tada:
