### ISSUE TITLE
Funcionamento das comparações

### ISSUE THREAD

**Issue by asfernandes** [aripiprazole/rinha-de-compiler#181]
Falta detalhar como as comparações devem funcionar com tipos diferentes, exemplos:
- `1 == "1"`
- `1 == (1, 2)`

**Comment by algebraic-sofia** [comment]
Foi detalhado o comportamento de algumas coisas que devem ser válidas. Tudo além disso é considerado undefined behaviour.

**Comment by algebraic-sofia** [comment]
O SPECS.md foi atualizado para especificar que tudo que não foi especificado deve dar erro.
