### ISSUE TITLE
Pacotes da máquina ubuntu

### ISSUE THREAD

**Issue by D4yvid** [aripiprazole/rinha-de-compiler#22]
A máquina ubuntu vai ter um compilador de C/C++ ou um linker e um assembler?

**Comment by lucasew** [comment]
Teremos docker?

**Comment by dhrleandro** [comment]
o README.MD mudou e removeu a palavra Ubuntu. Deixando apenas na especificação uma máquina com 2GB de memória e 2 núcleos de CPU.

Me parece que você terá que criar o seu container em um Dockerfile com tudo que precisa para rodar sua aplicação. A linguagem em si não importa, podendo ser C/C++ com compilador GCC, Python, Node.js, PHP, etc.

Eu acho que se executar este comando no Docker você conseguirá simular essas restrições de hardware:
```sh
docker run -it --memory="2g" --memory-swap="0" --cpus="2" NOME-DA-SUA-IMAGEM-DOCKER
```

**Comment by algebraic-sofia** [comment]
Cada projeto tem que ter seu proprio Dockerfile especificando seus pacotes.
