### ISSUE TITLE
Erro em TESTS.md

### ISSUE THREAD

**Issue by asfernandes** [aripiprazole/rinha-de-compiler#291]
Meu dockerfile builda corretamente com `docker build -t rinha-de-compiler .` mas está listado como problemático.

Acredito que o repositório foi clonado sem `--recurse-submodules`.

Foi falado que seria usado essa opção.

**Comment by algebraic-sofia** [comment]
Vou tentar adicionar o recurse submodules na ferramenta.

**Comment by RalphVita** [comment]
Oi, aconteceu o mesmo com o meu.
Está listado com X, mas sem log.
![image](https://github.com/aripiprazole/rinha-de-compiler/assets/12721445/6915ebd1-87b3-4960-9380-a95eebf7a86b)
Será que faltou só trocar o ícone do status? :)

**Comment by algebraic-sofia** [comment]
@RalphVita Apesar do seu rodar, ele não gera dados :S então pode ser que ele não esteja executando o código correto.

**Comment by RalphVita** [comment]
Valeu @algebraic-sofia,
Olhei aqui agora. 
E a minha branch main estava com uma versão do docker file comentada, que eu tinha feito só de teste, e acabei commitando. 
![image](https://github.com/aripiprazole/rinha-de-compiler/assets/12721445/98cf9702-dbd4-459b-a2aa-2ebf1f31a022)
