### ISSUE TITLE
Eu não sei qual link eu devo colocar para o repositório ser clonado

### ISSUE THREAD

**Issue by SamuelHaidu** [aripiprazole/rinha-de-compiler#294]
Inicialmente eu coloquei mandei esse link

https://github.com/SamuelHaidu/RinhaToPythonVM/tree/main

Deu o erro "cannot clone repository"

De fato rodando git clone com esse link da isso aqui:

```
PS D:\Projects> git clone https://github.com/SamuelHaidu/RinhaToPythonVM/tree/main
Cloning into 'main'...
fatal: repository 'https://github.com/SamuelHaidu/RinhaToPythonVM/tree/main/' not found
```

Mas ai fiz um pull request #287 para trocar para o https://github.com/SamuelHaidu/RinhaToPythonVM.git

Ai rodando aqui deu:
```
PS D:\Projects> git clone https://github.com/SamuelHaidu/RinhaToPythonVM.git
Cloning into 'RinhaToPythonVM'...
remote: Enumerating objects: 234, done.
remote: Counting objects: 100% (234/234), done.
remote: Compressing objects: 100% (140/140), done.
remote: Total 234 (delta 116), reused 199 (delta 82), pack-reused 0
Receiving objects: 100% (234/234), 42.73 KiB | 2.51 MiB/s, done.
Resolving deltas: 100% (116/116), done.
PS D:\Projects>
```

Porém ontem subiram no TESTS.md que o repositório não foi encontrado:
`cannot clone repository 'unexpected http status code: 404'`

Ai já não sei mais o que é, pois parece que agora nem encontrou nada no endereço http :(

**Comment by quatroka** [comment]
No primeiro link você utilizou a url apontando diretamente para a branch `main`, o certo seria apenas o link do reposítorio sem especificar a branch. Creio que o correto seria `https://github.com/SamuelHaidu/RinhaToPythonVM`
