### ISSUE TITLE
Sugestão: Playlist de aula de compiladores

### ISSUE THREAD

**Issue by MarlonHenq** [aripiprazole/rinha-de-compiler#3]
Sugestão de adicionar essa playlist de aulas sobre compiladores, é a mesma utilizada pela [UBL](https://github.com/Universidade-Livre/ciencia-da-computacao):

https://www.youtube.com/playlist?list=PLjcmNukBom6--0we1zrpoUE2GuRD-Me6W

**Comment by edusporto** [comment]
Gostaria de recomendar também o livro [Programming Languages: Application and Interpretation](https://www.plai.org/) pro pessoal que fala inglês, é escrito por um dos grandes professores da área de Linguagens de Programação e também serve como uma ótima introdução às linguagens da família Lisp.

**Comment by algebraic-sofia** [comment]
Foram adicionados :) mt obg
