### ISSUE TITLE
Especificação de `Var` faltando

### ISSUE THREAD

**Issue by edusporto** [aripiprazole/rinha-de-compiler#4]
Oi!

No arquivo [SPECS.md](https://github.com/aripiprazole/rinha-de-compiler/blob/727f3bb2b3554a4ba0fcb6ec8610a3031e061c5f/SPECS.md) está faltando a especificação pro termo `Var`.

É bem rápido de arrumar, posso fazer um PR caso queiram :)

**Comment by jeffque** [comment]
Não vi uso do var. onde você viu a necessidade dele? No LALR?

**Comment by jeffque** [comment]
Achei https://github.com/aripiprazole/rinha-de-compiler/blob/727f3bb2b3554a4ba0fcb6ec8610a3031e061c5f/src/ast.rs#L260
