### ISSUE TITLE
O print não deveria ter um "next"?

### ISSUE THREAD

**Issue by RRFreitas** [aripiprazole/rinha-de-compiler#49]
Acredito que o print, assim como o let, deveria haver um "next" para o próximo comando. Se não, não poderíamos colocar mais de um print no código.

**Comment by leonardohn** [comment]
Mas já é possível colocar mais de um, é só usar a expressão `let _ = print("");`.

**Comment by algebraic-sofia** [comment]
Fechando a issue já que a explicação do leonardohn está correta.
