### ISSUE TITLE
[Sugestão] Discord Server

### ISSUE THREAD

**Issue by Edu0liver** [aripiprazole/rinha-de-compiler#7]
Se a rinha, além do intuito competitivo claro, tiver a intenção de ajudar novas pessoas a entenderem esse mundo (educativo),
eu sugeriria a criação de um servidor no discord pra facilitar a interação. Mas fica a critério de vocês

**Comment by Losty17** [comment]
+1, seria bacana ter um espaço pra poder conversar sobre esses tópicos mais complexos

**Comment by Edu0liver** [comment]
Até para compartilhamento de conteúdo, avisos importantes quanto ao andamento da rinha e interação do pessoal :)

**Comment by aripiprazole** [comment]
oii, fizemos um server https://discord.gg/x5N9NhBwtX
